/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReturnSubmittedEvent struct {
	Payment *Payment `json:"payment,omitempty"`

	ReturnPayment *ReturnPayment `json:"return_payment,omitempty"`

	ReturnSubmission *ReturnSubmission `json:"return_submission,omitempty"`
}
