/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PositionAttributes struct {
	Scheme string `json:"scheme,omitempty"`

	Limit string `json:"limit,omitempty"`

	Position string `json:"position,omitempty"`
}
