/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ResourceType string

// List of ResourceType
const (
	PAYPORT_ASSOCIATIONS ResourceType = "payport_associations"
	LIMITS               ResourceType = "limits"
	BACS_ASSOCIATIONS    ResourceType = "bacs_associations"
)
