/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SettlementCycleType string

// List of SettlementCycleType
const (
	DAILY      SettlementCycleType = "daily"
	PER_SCHEME SettlementCycleType = "per_scheme"
)
