/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PayportParticipantType string

// List of PayportParticipantType
const (
	SETTLING     PayportParticipantType = "settling"
	NON_SETTLING PayportParticipantType = "non_settling"
)
