/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReturnReversalAdmissionAttributes struct {
	SourceGateway string `json:"source_gateway,omitempty"`

	SchemeStatusCode string `json:"scheme_status_code,omitempty"`
}
