/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// The payment admission resource related to the payment
type PaymentRelationshipsPaymentAdmission struct {
	Data []PaymentAdmission `json:"data,omitempty"`
}
