/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReversalPaymentRelationships struct {
	Payment *RelationshipLinks `json:"payment,omitempty"`

	ReversalAdmission *RelationshipLinks `json:"reversal_admission,omitempty"`
}
