/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BacsAssociationAttributes struct {
	ServiceUserNumber string `json:"service_user_number,omitempty"`

	AccountNumber string `json:"account_number,omitempty"`

	SortingCode string `json:"sorting_code,omitempty"`

	AccountType int32 `json:"account_type,omitempty"`

	BankCode string `json:"bank_code,omitempty"`

	CentreNumber string `json:"centre_number,omitempty"`
}
