/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ReturnPaymentAttributes struct {
	Amount string `json:"amount,omitempty"`

	Currency string `json:"currency,omitempty"`

	ReturnCode string `json:"return_code,omitempty"`

	SchemeTransactionId string `json:"scheme_transaction_id,omitempty"`

	LimitBreachStartDatetime time.Time `json:"limit_breach_start_datetime,omitempty"`

	LimitBreachEndDatetime time.Time `json:"limit_breach_end_datetime,omitempty"`
}
