/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AssociationAttributes struct {
	StarlingAccountUid string `json:"starling_account_uid,omitempty"`

	StarlingAccountName string `json:"starling_account_name,omitempty"`
}
