/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ValidationSource string

// List of ValidationSource
const (
	PAYMENT_API       ValidationSource = "payment_api"
	PAYPORT_INTERFACE ValidationSource = "payport_interface"
	STARLING_GATEWAY  ValidationSource = "starling_gateway"
	BACS_GATEWAY      ValidationSource = "bacs_gateway"
)
