/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PaymentAdmissionStatusReason string

// List of PaymentAdmissionStatusReason
const (
	PAYMENT_ADMISSION_STATUS_ACCEPTED                    PaymentAdmissionStatusReason = "accepted"
	PAYMENT_ADMISSION_STATUS_INVALID_BENEFICIARY_DETAILS PaymentAdmissionStatusReason = "invalid_beneficiary_details"
	PAYMENT_ADMISSION_STATUS_BANKID_NOT_PROVISIONED      PaymentAdmissionStatusReason = "bankid_not_provisioned"
	PAYMENT_ADMISSION_STATUS_UNKNOWN_ACCOUNTNUMBER       PaymentAdmissionStatusReason = "unknown_accountnumber"
)
