/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AceAttributes struct {
	RoleId string `json:"role_id,omitempty"`

	Action string `json:"action,omitempty"`

	RecordType string `json:"record_type,omitempty"`

	Filter string `json:"filter,omitempty"`
}
