/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type PaymentAdmissionAttributes struct {
	Status *PaymentAdmissionStatus `json:"status,omitempty"`

	SchemeStatusCode string `json:"scheme_status_code,omitempty"`

	StatusReason *PaymentAdmissionStatusReason `json:"status_reason,omitempty"`

	AdmissionDatetime time.Time `json:"admission_datetime,omitempty"`

	SettlementDate string `json:"settlement_date,omitempty"`

	SettlementCycle int32 `json:"settlement_cycle,omitempty"`
}
