/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PaymentAdmissionStatusReason string

// List of PaymentAdmissionStatusReason
const (
	ACCEPTED                    PaymentAdmissionStatusReason = "accepted"
	INVALID_BENEFICIARY_DETAILS PaymentAdmissionStatusReason = "invalid_beneficiary_details"
	BANKID_NOT_PROVISIONED      PaymentAdmissionStatusReason = "bankid_not_provisioned"
	UNKNOWN_ACCOUNTNUMBER       PaymentAdmissionStatusReason = "unknown_accountnumber"
)
