/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BankIdCode string

// List of BankIdCode
const (
	SWBIC BankIdCode = "SWBIC"
	GBDSC BankIdCode = "GBDSC"
	BE    BankIdCode = "BE"
	FR    BankIdCode = "FR"
	DEBLZ BankIdCode = "DEBLZ"
	GRBIC BankIdCode = "GRBIC"
	ITNCC BankIdCode = "ITNCC"
	PLKNR BankIdCode = "PLKNR"
	PTNCC BankIdCode = "PTNCC"
	ESNCC BankIdCode = "ESNCC"
	CHBCC BankIdCode = "CHBCC"
)
