/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PayportAssociationAttributes struct {
	ParticipantId string `json:"participant_id,omitempty"`

	ParticipantType *PayportParticipantType `json:"participant_type,omitempty"`

	CustomerSendingFpsInstitution string `json:"customer_sending_fps_institution,omitempty"`

	SponsorBankId string `json:"sponsor_bank_id,omitempty"`

	SponsorAccountNumber string `json:"sponsor_account_number,omitempty"`
}
