/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SettlementCycleAttributes struct {
	Gateway string `json:"gateway,omitempty"`

	SettlementCycleType string `json:"settlement_cycle_type,omitempty"`

	SettlementCycleNumber int32 `json:"settlement_cycle_number,omitempty"`
}
