/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type BacsAssociationCertificateRelationshipData struct {
	Type_ string `json:"type,omitempty"`

	KeyId string `json:"key_id,omitempty"`

	CertificateId string `json:"certificate_id,omitempty"`
}
