/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VocalinkReportAssociationAttributes struct {
	BacsServiceUserNumber string `json:"bacs_service_user_number,omitempty"`
}
