/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ChargesInformation struct {
	BearerCode string `json:"bearer_code,omitempty"`

	ReceiverChargesAmount string `json:"receiver_charges_amount,omitempty"`

	ReceiverChargesCurrency string `json:"receiver_charges_currency,omitempty"`

	SenderCharges []ChargesInformationSenderCharges `json:"sender_charges,omitempty"`
}
