/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type KeyAttributes struct {
	Subject string `json:"subject,omitempty"`

	PrivateKey string `json:"private_key,omitempty"`

	PublicKey string `json:"public_key,omitempty"`

	Description string `json:"description,omitempty"`

	CertificateSigningRequest string `json:"certificate_signing_request,omitempty"`
}
