/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PaymentRelationships struct {
	PaymentSubmission *PaymentRelationshipsPaymentSubmission `json:"payment_submission,omitempty"`

	PaymentReturn *PaymentRelationshipsPaymentReturn `json:"payment_return,omitempty"`

	PaymentAdmission *PaymentRelationshipsPaymentAdmission `json:"payment_admission,omitempty"`

	PaymentReversal *PaymentRelationshipsPaymentReversal `json:"payment_reversal,omitempty"`
}
