/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type ApprovalRequestAttributes struct {
	RecordType string `json:"record_type,omitempty"`

	RecordId string `json:"record_id,omitempty"`

	RecordOrgid string `json:"record_orgid,omitempty"`

	RecordVersion int32 `json:"record_version,omitempty"`

	Action string `json:"action,omitempty"`

	Status string `json:"status,omitempty"`

	ActionedBy string `json:"actioned_by,omitempty"`

	ActionTime time.Time `json:"action_time,omitempty"`

	BeforeData *interface{} `json:"before_data,omitempty"`

	AfterData *interface{} `json:"after_data,omitempty"`
}
