/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ReturnSubmissionStatus string

// List of ReturnSubmissionStatus
const (
	RETURN_SUBMISSION_STATUS_ACCEPTED            ReturnSubmissionStatus = "accepted"
	RETURN_SUBMISSION_STATUS_LIMIT_CHECK_PENDING ReturnSubmissionStatus = "limit_check_pending"
	RETURN_SUBMISSION_STATUS_LIMIT_CHECK_FAILED  ReturnSubmissionStatus = "limit_check_failed"
	RETURN_SUBMISSION_STATUS_LIMIT_CHECK_PASSED  ReturnSubmissionStatus = "limit_check_passed"
	RETURN_SUBMISSION_STATUS_RELEASED_TO_GATEWAY ReturnSubmissionStatus = "released_to_gateway"
	RETURN_SUBMISSION_STATUS_DELIVERY_CONFIRMED  ReturnSubmissionStatus = "delivery_confirmed"
	RETURN_SUBMISSION_STATUS_DELIVERY_FAILED     ReturnSubmissionStatus = "delivery_failed"
	RETURN_SUBMISSION_STATUS_SUBMITTED           ReturnSubmissionStatus = "submitted"
	RETURN_SUBMISSION_STATUS_VALIDATION_PENDING  ReturnSubmissionStatus = "validation_pending"
)
