/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SepaInstantAssociationAttributes struct {
	BusinessUserDn string `json:"business_user_dn,omitempty"`

	TransportProfileId string `json:"transport_profile_id,omitempty"`

	Bic string `json:"bic,omitempty"`
}
