/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LimitDetailsListResponse struct {
	Data []Limit `json:"data,omitempty"`

	Links *Links `json:"links,omitempty"`

	Meta *RecordCount `json:"meta,omitempty"`
}
