/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type SubscriptionAttributes struct {
	CallbackUri string `json:"callback_uri,omitempty"`

	CallbackTransport string `json:"callback_transport,omitempty"`

	UserId string `json:"user_id,omitempty"`

	RecordType string `json:"record_type,omitempty"`

	EventType string `json:"event_type,omitempty"`
}
