/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Links struct {
	Self string `json:"self,omitempty"`

	First string `json:"first,omitempty"`

	Prev string `json:"prev,omitempty"`

	Next string `json:"next,omitempty"`

	Last string `json:"last,omitempty"`
}
