/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LimitAttributes struct {
	Gateway string `json:"gateway,omitempty"`

	Scheme string `json:"scheme,omitempty"`

	Amount string `json:"amount,omitempty"`

	SettlementCycleType *SettlementCycleType `json:"settlement_cycle_type,omitempty"`
}
