/*
 * Payment Server.
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type VocalinkReportAssociationRelationships struct {
	BacsMemberCertificate *VocalinkReportAssociationCertificateRelationship `json:"bacs_member_certificate,omitempty"`

	BacsServiceUserCertificate *VocalinkReportAssociationCertificateRelationship `json:"bacs_service_user_certificate,omitempty"`

	FpsMemberCertificate *VocalinkReportAssociationCertificateRelationship `json:"fps_member_certificate,omitempty"`
}
